version: '2.1'
services: 
    ecsfargatecoreapi:
        build:
            context:  ./ecsfargatecoreapi
            dockerfile: Dockerfile
        expose: 
            - "5000"
        restart: always
    reverseproxy:
        build: 
            context: ./reverseproxy
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        restart: always
        links: 
            - ecsfargatecoreapi
